# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'meredith-service-connection'
    appType: webApp
    appName: 'meredith-pipeline-war'
    package: '$(System.DefaultWorkingDirectory)/**/*.war'


# Start, stop, restart, slot swap, slot delete, install site extensions or enable continuous monitoring for an Azure App Service
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'meredith-service-connection'
    action: 'Swap Slots' # Optional. Options: swap Slots, start Azure App Service, stop Azure App Service, restart Azure App Service, delete Slot, install Extensions, enable Continuous Monitoring, start All Continuous Webjobs, stop All Continuous Webjobs
    webAppName: 'meredith-pipeline-war'
    #specifySlotOrASE: false # Optional
    resourceGroupName: 'meredith-test'# Required when action == Swap Slots || Action == Delete Slot || SpecifySlot == True
    sourceSlot: 'meredith-pipeline-war-test' # Required when action == Swap Slots
    swapWithProduction: true # Optional
    targetSlot: meredith-pipeline-war # Required when action == Swap Slots && SwapWithProduction == False
    #preserveVnet: false # Optional
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-manage?view=azure-devops
